// Dish profiles: data-driven recipe generation
// Each profile defines a dish template with base ingredient, required companions, and preferred optional companions

export interface DishProfile {
  id: string;
  name: string;
  cuisine: string;
  mealType: string;
  baseIngredient: string;
  companions: {
    required: string[];
    preferred: string[];
  };
  cookingMethod: string;
  time: number;
  difficulty: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  description: string;
  stepKey: string;
}

export const dishProfiles: DishProfile[] = [
  // ==================== BREAKFAST ====================

  // Egg dishes
  {
    id: 'veg-omelette',
    name: 'Vegetable Omelette',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    baseIngredient: 'egg',
    companions: { required: [], preferred: ['onion', 'tomato', 'capsicum', 'chili', 'ginger', 'coriander leaves'] },
    cookingMethod: 'fry',
    time: 10,
    difficulty: 'Easy',
    calories: 220, protein: 16, carbs: 6, fat: 14, fiber: 2,
    description: 'Fluffy eggs with chopped vegetables and spices — quick protein-packed breakfast',
    stepKey: 'omelette',
  },
  {
    id: 'egg-bhurji',
    name: 'Egg Bhurji',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    baseIngredient: 'egg',
    companions: { required: ['onion'], preferred: ['tomato', 'chili', 'ginger', 'coriander leaves'] },
    cookingMethod: 'scramble',
    time: 10,
    difficulty: 'Easy',
    calories: 250, protein: 18, carbs: 8, fat: 16, fiber: 3,
    description: 'Scrambled eggs with onions, tomatoes and Indian spices — hearty breakfast',
    stepKey: 'egg',
  },

  // Roti/Paratha dishes
  {
    id: 'plain-roti',
    name: 'Plain Roti with Sabzi',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    baseIngredient: 'flour',
    companions: { required: [], preferred: ['onion', 'tomato', 'potato', 'capsicum'] },
    cookingMethod: 'roll',
    time: 20,
    difficulty: 'Medium',
    calories: 280, protein: 8, carbs: 48, fat: 6, fiber: 4,
    description: 'Soft wheat flatbread served with spiced vegetable curry — everyday staple',
    stepKey: 'vegetable',
  },
  {
    id: 'onion-paratha',
    name: 'Onion Paratha',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    baseIngredient: 'flour',
    companions: { required: ['onion'], preferred: ['potato', 'capsicum', 'green chili'] },
    cookingMethod: 'stuff-roll',
    time: 25,
    difficulty: 'Medium',
    calories: 320, protein: 9, carbs: 42, fat: 12, fiber: 5,
    description: 'Stuffed flatbread with spiced onion filling — crispy, buttery breakfast',
    stepKey: 'lemon',
  },
  {
    id: 'aloo-paratha',
    name: 'Aloo Paratha',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    baseIngredient: 'flour',
    companions: { required: ['potato'], preferred: ['onion', 'green chili', 'coriander leaves'] },
    cookingMethod: 'stuff-roll',
    time: 30,
    difficulty: 'Medium',
    calories: 350, protein: 9, carbs: 50, fat: 12, fiber: 5,
    description: 'Stuffed flatbread with spiced potato filling — classic North Indian breakfast',
    stepKey: 'potato',
  },
  {
    id: 'capsicum-paratha',
    name: 'Capsicum Paratha',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    baseIngredient: 'flour',
    companions: { required: ['capsicum'], preferred: ['onion', 'green chili', 'corn'] },
    cookingMethod: 'stuff-roll',
    time: 25,
    difficulty: 'Medium',
    calories: 300, protein: 8, carbs: 44, fat: 10, fiber: 5,
    description: 'Stuffed flatbread with spiced capsicum filling — colorful and nutritious',
    stepKey: 'capsicum',
  },

  // Bread dishes
  {
    id: 'bread-omelette',
    name: 'Bread Omelette',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    baseIngredient: 'bread',
    companions: { required: ['egg'], preferred: ['onion', 'tomato', 'chili'] },
    cookingMethod: 'fry',
    time: 10,
    difficulty: 'Easy',
    calories: 280, protein: 14, carbs: 24, fat: 14, fiber: 2,
    description: 'Omelette sandwich between two slices of bread — quick kid-friendly breakfast',
    stepKey: 'omelette',
  },
  {
    id: 'bread-toast',
    name: 'Vegetable Toast',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    baseIngredient: 'bread',
    companions: { required: ['butter'], preferred: ['onion', 'tomato', 'chili', 'cheese'] },
    cookingMethod: 'toast',
    time: 8,
    difficulty: 'Easy',
    calories: 200, protein: 6, carbs: 22, fat: 10, fiber: 3,
    description: 'Toasted bread topped with spiced vegetables and butter — simple breakfast',
    stepKey: 'vegetable',
  },

  // Dosa/Chilla dishes
  {
    id: 'masala-dosa',
    name: 'Masala Dosa',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    baseIngredient: 'flour',
    companions: { required: ['potato'], preferred: ['onion', 'turmeric', 'curry leaves'] },
    cookingMethod: 'pan-fry',
    time: 30,
    difficulty: 'Medium',
    calories: 290, protein: 7, carbs: 48, fat: 8, fiber: 4,
    description: 'Crispy rice crepe stuffed with spiced potato — South Indian breakfast classic',
    stepKey: 'potato',
  },
  {
    id: 'onion-chilla',
    name: 'Onion Chilla',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    baseIngredient: 'gram flour',
    companions: { required: ['onion'], preferred: ['tomato', 'chili', 'coriander leaves'] },
    cookingMethod: 'pan-fry',
    time: 15,
    difficulty: 'Easy',
    calories: 200, protein: 12, carbs: 18, fat: 10, fiber: 5,
    description: 'Savory gram flour pancake with onions — protein-rich healthy breakfast',
    stepKey: 'vegetable',
  },

  // Yogurt dishes
  {
    id: 'yogurt-breakfast',
    name: 'Spiced Yogurt Bowl',
    cuisine: 'Indian',
    mealType: 'Breakfast',
    baseIngredient: 'yogurt',
    companions: { required: [], preferred: ['onion', 'tomato', 'cucumber', 'coriander leaves'] },
    cookingMethod: 'mix',
    time: 5,
    difficulty: 'Easy',
    calories: 150, protein: 10, carbs: 12, fat: 6, fiber: 2,
    description: 'Fresh yogurt with roasted cumin, salt and chopped vegetables — light breakfast',
    stepKey: 'curd',
  },

  // ==================== LUNCH ====================

  // Rice dishes
  {
    id: 'lemon-rice',
    name: 'Lemon Rice',
    cuisine: 'Indian',
    mealType: 'Lunch',
    baseIngredient: 'rice',
    companions: { required: [], preferred: ['lemon', 'peanut', 'mustard seed', 'turmeric', 'curry leaves', 'chili'] },
    cookingMethod: 'boil-temper',
    time: 20,
    difficulty: 'Easy',
    calories: 280, protein: 5, carbs: 48, fat: 8, fiber: 3,
    description: 'Tangy lemon rice tempered with mustard seeds, peanuts and curry leaves — South Indian classic',
    stepKey: 'lemon',
  },
  {
    id: 'tomato-rice',
    name: 'Tomato Rice',
    cuisine: 'Indian',
    mealType: 'Lunch',
    baseIngredient: 'rice',
    companions: { required: ['tomato'], preferred: ['onion', 'chili', 'turmeric', 'coriander leaves'] },
    cookingMethod: 'boil-temper',
    time: 25,
    difficulty: 'Easy',
    calories: 260, protein: 6, carbs: 46, fat: 6, fiber: 3,
    description: 'Flavorful rice cooked with fresh tomatoes and aromatic spices',
    stepKey: 'tomato',
  },
  {
    id: 'aloo-jeera-rice',
    name: 'Aloo Jeera Rice',
    cuisine: 'Indian',
    mealType: 'Lunch',
    baseIngredient: 'rice',
    companions: { required: ['potato'], preferred: ['cumin', 'turmeric', 'coriander', 'chili', 'coriander leaves'] },
    cookingMethod: 'boil-temper',
    time: 25,
    difficulty: 'Easy',
    calories: 300, protein: 7, carbs: 52, fat: 8, fiber: 4,
    description: 'Cumin-spiced rice with crispy potato cubes — simple, aromatic, filling',
    stepKey: 'potato',
  },
  {
    id: 'veg-pulao',
    name: 'Mixed Vegetable Pulao',
    cuisine: 'Indian',
    mealType: 'Lunch',
    baseIngredient: 'rice',
    companions: { required: [], preferred: ['potato', 'carrot', 'peas', 'capsicum', 'cumin', 'turmeric', 'coriander'] },
    cookingMethod: 'boil',
    time: 30,
    difficulty: 'Easy',
    calories: 320, protein: 8, carbs: 54, fat: 8, fiber: 5,
    description: 'One-pot rice cooked with mixed vegetables and whole spices — complete meal',
    stepKey: 'vegetable',
  },
  {
    id: 'curd-rice',
    name: 'Curd Rice',
    cuisine: 'Indian',
    mealType: 'Lunch',
    baseIngredient: 'rice',
    companions: { required: ['yogurt'], preferred: ['butter', 'mustard seed', 'curry leaves', 'chili', 'cashew'] },
    cookingMethod: 'mix-temper',
    time: 20,
    difficulty: 'Easy',
    calories: 250, protein: 8, carbs: 40, fat: 7, fiber: 2,
    description: 'Creamy cooled rice mixed with spiced yogurt — digestive comfort food',
    stepKey: 'curd',
  },
  {
    id: 'coconut-rice',
    name: 'Coconut Rice',
    cuisine: 'Indian',
    mealType: 'Lunch',
    baseIngredient: 'rice',
    companions: { required: ['coconut'], preferred: ['peanut', 'mustard seed', 'curry leaves', 'chili', 'cashew'] },
    cookingMethod: 'mix-temper',
    time: 20,
    difficulty: 'Easy',
    calories: 310, protein: 6, carbs: 46, fat: 12, fiber: 3,
    description: 'Flavorful rice mixed with fresh coconut, peanuts and tempered spices',
    stepKey: 'lemon',
  },
  {
    id: 'egg-fried-rice',
    name: 'Egg Fried Rice',
    cuisine: 'Indo-Chinese',
    mealType: 'Lunch',
    baseIngredient: 'rice',
    companions: { required: ['egg'], preferred: ['onion', 'soy sauce', 'chili', 'capsicum', 'carrot'] },
    cookingMethod: 'stir-fry',
    time: 15,
    difficulty: 'Easy',
    calories: 350, protein: 14, carbs: 48, fat: 12, fiber: 3,
    description: 'Quick wok-fried rice with scrambled eggs, onions and soy sauce',
    stepKey: 'egg',
  },
  {
    id: 'capsicum-fried-rice',
    name: 'Capsicum Fried Rice',
    cuisine: 'Indo-Chinese',
    mealType: 'Lunch',
    baseIngredient: 'rice',
    companions: { required: ['capsicum'], preferred: ['onion', 'soy sauce', 'chili', 'carrot'] },
    cookingMethod: 'stir-fry',
    time: 15,
    difficulty: 'Easy',
    calories: 300, protein: 6, carbs: 50, fat: 10, fiber: 4,
    description: 'Wok-fried rice with colorful capsicum, onions and Asian spices',
    stepKey: 'capsicum',
  },

  // Noodle dishes
  {
    id: 'chowmein',
    name: 'Vegetable Chowmein',
    cuisine: 'Indo-Chinese',
    mealType: 'Lunch',
    baseIngredient: 'noodles',
    companions: { required: ['onion', 'capsicum'], preferred: ['carrot', 'cabbage', 'soy sauce', 'chili', 'garlic'] },
    cookingMethod: 'stir-fry',
    time: 15,
    difficulty: 'Easy',
    calories: 340, protein: 10, carbs: 52, fat: 12, fiber: 5,
    description: 'Stir-fried noodles with mixed vegetables in soy-garlic sauce — street food favorite',
    stepKey: 'vegetable',
  },
  {
    id: 'hakka-noodles',
    name: 'Hakka Noodles',
    cuisine: 'Indo-Chinese',
    mealType: 'Lunch',
    baseIngredient: 'noodles',
    companions: { required: ['carrot', 'cabbage'], preferred: ['onion', 'capsicum', 'soy sauce', 'chili', 'garlic'] },
    cookingMethod: 'stir-fry',
    time: 15,
    difficulty: 'Easy',
    calories: 330, protein: 9, carbs: 50, fat: 11, fiber: 5,
    description: 'Tossed noodles with shredded vegetables in light soy seasoning — clean and flavorful',
    stepKey: 'vegetable',
  },
  {
    id: 'noodles-soup',
    name: 'Noodles in Soup',
    cuisine: 'Indo-Chinese',
    mealType: 'Lunch',
    baseIngredient: 'noodles',
    companions: { required: ['onion'], preferred: ['carrot', 'capsicum', 'soy sauce', 'garlic', 'chili'] },
    cookingMethod: 'boil-soup',
    time: 15,
    difficulty: 'Easy',
    calories: 260, protein: 8, carbs: 42, fat: 6, fiber: 4,
    description: 'Hot noodle soup with vegetables, ginger and soy sauce — warming comfort food',
    stepKey: 'vegetable',
  },
  {
    id: 'egg-chowmein',
    name: 'Egg Chowmein',
    cuisine: 'Indo-Chinese',
    mealType: 'Lunch',
    baseIngredient: 'noodles',
    companions: { required: ['egg', 'onion'], preferred: ['capsicum', 'carrot', 'soy sauce', 'chili'] },
    cookingMethod: 'stir-fry',
    time: 15,
    difficulty: 'Easy',
    calories: 380, protein: 16, carbs: 50, fat: 14, fiber: 4,
    description: 'Stir-fried noodles with scrambled eggs and vegetables — protein-packed lunch',
    stepKey: 'egg',
  },

  // Pasta dishes
  {
    id: 'pasta-tomato',
    name: 'Pasta Arrabiata',
    cuisine: 'Italian',
    mealType: 'Lunch',
    baseIngredient: 'pasta',
    companions: { required: ['tomato'], preferred: ['garlic', 'onion', 'chili', 'olive oil'] },
    cookingMethod: 'boil-sauce',
    time: 25,
    difficulty: 'Easy',
    calories: 380, protein: 12, carbs: 62, fat: 10, fiber: 5,
    description: 'Pasta in spicy tomato sauce with garlic and chili — classic Italian',
    stepKey: 'tomato',
  },
  {
    id: 'pasta-aglio-olio',
    name: 'Pasta Aglio Olio',
    cuisine: 'Italian',
    mealType: 'Lunch',
    baseIngredient: 'pasta',
    companions: { required: ['garlic', 'oil'], preferred: ['chili', 'onion', 'parsley'] },
    cookingMethod: 'boil-toss',
    time: 20,
    difficulty: 'Easy',
    calories: 350, protein: 10, carbs: 55, fat: 12, fiber: 3,
    description: 'Pasta tossed with garlic, olive oil and chili flakes — simple Italian classic',
    stepKey: 'vegetable',
  },
  {
    id: 'pasta-veg',
    name: 'Vegetable Pasta',
    cuisine: 'Italian',
    mealType: 'Lunch',
    baseIngredient: 'pasta',
    companions: { required: [], preferred: ['capsicum', 'tomato', 'onion', 'garlic', 'mushroom', 'peas'] },
    cookingMethod: 'boil-toss',
    time: 20,
    difficulty: 'Easy',
    calories: 360, protein: 12, carbs: 58, fat: 10, fiber: 5,
    description: 'Pasta tossed with sautéed vegetables in garlic-olive oil sauce',
    stepKey: 'vegetable',
  },

  // Sabzi/curry dishes
  {
    id: 'onion-tomato-sabzi',
    name: 'Onion Tomato Sabzi',
    cuisine: 'Indian',
    mealType: 'Lunch',
    baseIngredient: 'onion',
    companions: { required: ['tomato'], preferred: ['potato', 'capsicum', 'garlic', 'ginger'] },
    cookingMethod: 'cook',
    time: 20,
    difficulty: 'Easy',
    calories: 160, protein: 4, carbs: 18, fat: 8, fiber: 5,
    description: 'Dry spiced onion-tomato vegetable — everyday Indian home cooking',
    stepKey: 'tomato',
  },
  {
    id: 'capsicum-sabzi',
    name: 'Capsicum Sabzi',
    cuisine: 'Indian',
    mealType: 'Lunch',
    baseIngredient: 'capsicum',
    companions: { required: ['onion'], preferred: ['tomato', 'garlic', 'chili'] },
    cookingMethod: 'stir-fry',
    time: 15,
    difficulty: 'Easy',
    calories: 140, protein: 4, carbs: 14, fat: 8, fiber: 5,
    description: 'Stir-fried capsicum with onions and Indian spices — quick side dish',
    stepKey: 'vegetable',
  },
  {
    id: 'potato-sabzi',
    name: 'Aloo Sabzi',
    cuisine: 'Indian',
    mealType: 'Lunch',
    baseIngredient: 'potato',
    companions: { required: ['onion'], preferred: ['tomato', 'garlic', 'ginger', 'turmeric'] },
    cookingMethod: 'cook',
    time: 20,
    difficulty: 'Easy',
    calories: 180, protein: 4, carbs: 28, fat: 7, fiber: 4,
    description: 'Classic spiced potato curry — the most common Indian home dish',
    stepKey: 'vegetable',
  },
  {
    id: 'mixed-veg-curry',
    name: 'Mixed Vegetable Curry',
    cuisine: 'Indian',
    mealType: 'Lunch',
    baseIngredient: 'potato',
    companions: { required: [], preferred: ['carrot', 'peas', 'capsicum', 'cauliflower', 'onion', 'tomato'] },
    cookingMethod: 'cook',
    time: 25,
    difficulty: 'Easy',
    calories: 200, protein: 6, carbs: 28, fat: 8, fiber: 7,
    description: 'Assorted vegetables cooked in spiced onion-tomato gravy — healthy and filling',
    stepKey: 'vegetable',
  },

  // ==================== DINNER ====================

  // Rice for dinner
  {
    id: 'veg-biryani',
    name: 'Vegetable Biryani',
    cuisine: 'Indian',
    mealType: 'Dinner',
    baseIngredient: 'rice',
    companions: { required: [], preferred: ['potato', 'carrot', 'peas', 'cauliflower', 'yogurt', 'biryani masala', 'ghee'] },
    cookingMethod: 'layer-cook',
    time: 40,
    difficulty: 'Medium',
    calories: 420, protein: 10, carbs: 65, fat: 14, fiber: 6,
    description: 'Fragrant layered rice with spiced vegetables — celebratory one-pot meal',
    stepKey: 'vegetable',
  },
  {
    id: 'dal-rice',
    name: 'Dal Rice (Tadka Dal)',
    cuisine: 'Indian',
    mealType: 'Dinner',
    baseIngredient: 'rice',
    companions: { required: ['lentils'], preferred: ['ghee', 'onion', 'garlic', 'tomato', 'turmeric'] },
    cookingMethod: 'boil-dal',
    time: 35,
    difficulty: 'Easy',
    calories: 380, protein: 14, carbs: 58, fat: 10, fiber: 8,
    description: 'Creamy spiced lentils served over steamed rice — comfort food staple',
    stepKey: 'vegetable',
  },

  // Noodles for dinner
  {
    id: 'veg-manchurian',
    name: 'Vegetable Manchurian',
    cuisine: 'Indo-Chinese',
    mealType: 'Dinner',
    baseIngredient: 'noodles',
    companions: { required: ['onion', 'capsicum'], preferred: ['garlic', 'soy sauce', 'chili', 'corn flour', 'carrot'] },
    cookingMethod: 'fry-sauce',
    time: 25,
    difficulty: 'Medium',
    calories: 360, protein: 12, carbs: 48, fat: 14, fiber: 5,
    description: 'Crispy vegetable balls in spicy soy-garlic sauce — Indo-Chinese restaurant favorite',
    stepKey: 'vegetable',
  },
  {
    id: 'noodles-dinner',
    name: 'Soy Noodles',
    cuisine: 'Indo-Chinese',
    mealType: 'Dinner',
    baseIngredient: 'noodles',
    companions: { required: ['onion'], preferred: ['capsicum', 'carrot', 'soy sauce', 'chili', 'garlic'] },
    cookingMethod: 'stir-fry',
    time: 15,
    difficulty: 'Easy',
    calories: 320, protein: 9, carbs: 48, fat: 10, fiber: 4,
    description: 'Quick soy sauce noodles with vegetables — late night comfort food',
    stepKey: 'vegetable',
  },

  // Paneer dishes
  {
    id: 'paneer-tikka-masala',
    name: 'Paneer Tikka Masala',
    cuisine: 'Indian',
    mealType: 'Dinner',
    baseIngredient: 'paneer',
    companions: { required: ['onion', 'tomato'], preferred: ['capsicum', 'yogurt', 'ginger', 'garlic', 'cream'] },
    cookingMethod: 'cook-gravy',
    time: 30,
    difficulty: 'Medium',
    calories: 380, protein: 18, carbs: 18, fat: 24, fiber: 5,
    description: 'Grilled paneer cubes in rich spiced onion-tomato gravy — restaurant-style dinner',
    stepKey: 'tomato',
  },
  {
    id: 'paneer-butter-masala',
    name: 'Butter Paneer',
    cuisine: 'Indian',
    mealType: 'Dinner',
    baseIngredient: 'paneer',
    companions: { required: ['tomato'], preferred: ['onion', 'butter', 'cream', 'garlic', 'cashew'] },
    cookingMethod: 'cook-gravy',
    time: 35,
    difficulty: 'Medium',
    calories: 420, protein: 16, carbs: 18, fat: 30, fiber: 4,
    description: 'Soft paneer in creamy tomato-butter gravy — rich indulgent dinner',
    stepKey: 'tomato',
  },

  // Chicken/meat dishes
  {
    id: 'chicken-curry',
    name: 'Chicken Curry',
    cuisine: 'Indian',
    mealType: 'Dinner',
    baseIngredient: 'chicken',
    companions: { required: ['onion', 'tomato'], preferred: ['garlic', 'ginger', 'turmeric', 'chili', 'yogurt'] },
    cookingMethod: 'cook-gravy',
    time: 35,
    difficulty: 'Medium',
    calories: 350, protein: 28, carbs: 14, fat: 20, fiber: 4,
    description: 'Classic chicken simmered in spiced onion-tomato gravy — everyday dinner',
    stepKey: 'tomato',
  },
  {
    id: 'chicken-biryani',
    name: 'Chicken Biryani',
    cuisine: 'Indian',
    mealType: 'Dinner',
    baseIngredient: 'chicken',
    companions: { required: ['rice'], preferred: ['onion', 'yogurt', 'biryani masala', 'ginger', 'garlic', 'mint'] },
    cookingMethod: 'layer-cook',
    time: 50,
    difficulty: 'Hard',
    calories: 520, protein: 30, carbs: 58, fat: 20, fiber: 5,
    description: 'Fragrant layered rice with spiced chicken — celebratory feast dish',
    stepKey: 'egg',
  },

  // ==================== SNACKS ====================

  // Fried snacks
  {
    id: 'veg-spring-roll',
    name: 'Vegetable Spring Roll',
    cuisine: 'Indo-Chinese',
    mealType: 'Snacks',
    baseIngredient: 'flour',
    companions: { required: ['cabbage', 'carrot'], preferred: ['onion', 'capsicum', 'soy sauce', 'chili', 'garlic'] },
    cookingMethod: 'roll-fry',
    time: 20,
    difficulty: 'Medium',
    calories: 220, protein: 6, carbs: 28, fat: 10, fiber: 4,
    description: 'Crispy pastry rolls filled with stir-fried vegetables — party favorite',
    stepKey: 'vegetable',
  },
  {
    id: 'corn-cobs',
    name: 'Corn Cobs',
    cuisine: 'Indo-Chinese',
    mealType: 'Snacks',
    baseIngredient: 'corn',
    companions: { required: ['butter'], preferred: ['chili', 'pepper', 'salt', 'lemon'] },
    cookingMethod: 'grill-fry',
    time: 15,
    difficulty: 'Easy',
    calories: 180, protein: 4, carbs: 22, fat: 8, fiber: 3,
    description: 'Grilled sweet corn seasoned with butter, chili and pepper — street food snack',
    stepKey: 'vegetable',
  },
  {
    id: 'potato-wedges',
    name: 'Masala Potato Wedges',
    cuisine: 'Indian',
    mealType: 'Snacks',
    baseIngredient: 'potato',
    companions: { required: [], preferred: ['oil', 'chili', 'garlic', 'coriander leaves', 'salt'] },
    cookingMethod: 'bake-fry',
    time: 25,
    difficulty: 'Easy',
    calories: 200, protein: 4, carbs: 30, fat: 8, fiber: 3,
    description: 'Spiced potato wedges baked until crispy — healthy snack alternative',
    stepKey: 'vegetable',
  },

  // Bread snacks
  {
    id: 'bread-sandwich',
    name: 'Vegetable Sandwich',
    cuisine: 'Indian',
    mealType: 'Snacks',
    baseIngredient: 'bread',
    companions: { required: ['butter'], preferred: ['onion', 'tomato', 'capsicum', 'cheese', 'chili'] },
    cookingMethod: 'toast',
    time: 10,
    difficulty: 'Easy',
    calories: 240, protein: 8, carbs: 28, fat: 12, fiber: 4,
    description: 'Grilled sandwich loaded with fresh vegetables and butter — quick snack',
    stepKey: 'vegetable',
  },
  {
    id: 'bread-masala-toast',
    name: 'Masala Toast',
    cuisine: 'Indian',
    mealType: 'Snacks',
    baseIngredient: 'bread',
    companions: { required: ['butter'], preferred: ['onion', 'chili', 'coriander leaves'] },
    cookingMethod: 'toast',
    time: 8,
    difficulty: 'Easy',
    calories: 220, protein: 6, carbs: 24, fat: 12, fiber: 3,
    description: 'Spiced butter toast with onions and herbs — tea-time favorite',
    stepKey: 'vegetable',
  },

  // Pakora/Chilla snacks
  {
    id: 'onion-pakora',
    name: 'Onion Pakora',
    cuisine: 'Indian',
    mealType: 'Snacks',
    baseIngredient: 'gram flour',
    companions: { required: ['onion'], preferred: ['chili', 'coriander leaves', 'spices'] },
    cookingMethod: 'deep-fry',
    time: 20,
    difficulty: 'Easy',
    calories: 240, protein: 7, carbs: 24, fat: 14, fiber: 4,
    description: 'Crispy onion fritters in gram flour batter — perfect chai companion',
    stepKey: 'vegetable',
  },
  {
    id: 'potato-pakora',
    name: 'Aloo Pakora',
    cuisine: 'Indian',
    mealType: 'Snacks',
    baseIngredient: 'gram flour',
    companions: { required: ['potato'], preferred: ['chili', 'coriander leaves', 'ginger'] },
    cookingMethod: 'deep-fry',
    time: 20,
    difficulty: 'Easy',
    calories: 260, protein: 6, carbs: 28, fat: 14, fiber: 4,
    description: 'Crispy potato fritters in spiced gram flour batter — addictive snack',
    stepKey: 'vegetable',
  },

  // Soup snacks
  {
    id: 'veg-soup',
    name: 'Vegetable Soup',
    cuisine: 'Indian',
    mealType: 'Snacks',
    baseIngredient: 'carrot',
    companions: { required: [], preferred: ['onion', 'capsicum', 'celery', 'garlic', 'pepper'] },
    cookingMethod: 'boil',
    time: 20,
    difficulty: 'Easy',
    calories: 120, protein: 4, carbs: 18, fat: 4, fiber: 5,
    description: 'Hot clear soup with mixed vegetables and herbs — light healthy snack',
    stepKey: 'vegetable',
  },
  {
    id: 'tomato-soup',
    name: 'Tomato Soup',
    cuisine: 'Indian',
    mealType: 'Snacks',
    baseIngredient: 'tomato',
    companions: { required: ['onion', 'garlic'], preferred: ['cream', 'basil', 'pepper', 'sugar'] },
    cookingMethod: 'blend',
    time: 25,
    difficulty: 'Easy',
    calories: 140, protein: 4, carbs: 20, fat: 5, fiber: 4,
    description: 'Creamy tomato soup with garlic and herbs — comforting classic',
    stepKey: 'tomato',
  },

  // ==================== DESSERTS / SWEET ====================

  {
    id: 'kheer',
    name: 'Rice Kheer',
    cuisine: 'Indian',
    mealType: 'Desserts',
    baseIngredient: 'rice',
    companions: { required: ['milk'], preferred: ['sugar', 'cardamom', 'cashew', 'raisin', 'pista'] },
    cookingMethod: 'boil-simmer',
    time: 40,
    difficulty: 'Easy',
    calories: 280, protein: 8, carbs: 42, fat: 8, fiber: 1,
    description: 'Sweet rice pudding cooked in reduced milk with nuts — festive dessert',
    stepKey: 'curd',
  },
  {
    id: 'fruit-chikki',
    name: 'Sweet Porridge',
    cuisine: 'Indian',
    mealType: 'Desserts',
    baseIngredient: 'oats',
    companions: { required: ['milk'], preferred: ['banana', 'sugar', 'cardamom', 'cashew'] },
    cookingMethod: 'boil',
    time: 15,
    difficulty: 'Easy',
    calories: 200, protein: 6, carbs: 36, fat: 5, fiber: 4,
    description: 'Sweet milk porridge with oats and banana — healthy dessert',
    stepKey: 'vegetable',
  },
];
