import { PrismaClient } from '@prisma/client';
import crypto from 'crypto';

const prisma = new PrismaClient();

const recipes = [
  { title: 'Butter Chicken', description: 'Creamy and rich Indian curry with tender chicken pieces in a tomato-based sauce', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 45, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 490, protein: 32, carbs: 18, fat: 34, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=butter+chicken+recipe' },
  { title: 'Margherita Pizza', description: 'Classic Italian pizza with fresh mozzarella, tomatoes, and basil', cuisine: 'Italian', mealType: 'Dinner', cookingTime: 30, servings: 2, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 350, protein: 15, carbs: 42, fat: 14, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=margherita+pizza+recipe' },
  { title: 'Vegetable Stir Fry', description: 'Quick and healthy Asian-style stir fry with fresh vegetables and soy sauce', cuisine: 'Chinese', mealType: 'Lunch', cookingTime: 15, servings: 2, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 220, protein: 8, carbs: 28, fat: 10, fiber: 6 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=vegetable+stir+fry+recipe' },
  { title: 'Banana Pancakes', description: 'Fluffy and sweet pancakes made with ripe bananas, perfect for breakfast', cuisine: 'American', mealType: 'Breakfast', cookingTime: 20, servings: 2, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 310, protein: 10, carbs: 48, fat: 8, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=banana+pancakes+recipe' },
  { title: 'Caesar Salad', description: 'Crispy romaine lettuce with creamy Caesar dressing, croutons, and parmesan', cuisine: 'American', mealType: 'Lunch', cookingTime: 15, servings: 2, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 280, protein: 12, carbs: 16, fat: 20, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=caesar+salad+recipe' },
  { title: 'Masala Dosa', description: 'Crispy South Indian crepe filled with spiced potato mixture', cuisine: 'Indian', mealType: 'Breakfast', cookingTime: 40, servings: 4, difficulty: 'Hard', nutritionalInfo: JSON.stringify({ calories: 380, protein: 8, carbs: 52, fat: 16, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=masala+dosa+recipe' },
  { title: 'Chocolate Mousse', description: 'Light, airy, and decadent chocolate dessert', cuisine: 'French', mealType: 'Desserts', cookingTime: 25, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 320, protein: 6, carbs: 35, fat: 18, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=chocolate+mousse+recipe' },
  { title: 'Chicken Biryani', description: 'Fragrant layered rice dish with spiced chicken, a classic Indian delicacy', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 60, servings: 6, difficulty: 'Hard', nutritionalInfo: JSON.stringify({ calories: 520, protein: 28, carbs: 58, fat: 22, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=chicken+biryani+recipe' },
  { title: 'Greek Salad', description: 'Fresh Mediterranean salad with feta cheese, olives, and vegetables', cuisine: 'Mediterranean', mealType: 'Lunch', cookingTime: 10, servings: 2, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 250, protein: 10, carbs: 14, fat: 18, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=greek+salad+recipe' },
  { title: 'Pasta Carbonara', description: 'Creamy Italian pasta with bacon, egg, and parmesan cheese', cuisine: 'Italian', mealType: 'Dinner', cookingTime: 25, servings: 3, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 480, protein: 24, carbs: 45, fat: 22, fiber: 2 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=pasta+carbonara+recipe' },
  { title: 'Chicken Curry', description: 'Spicy and flavorful chicken curry with tomatoes and onions', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 40, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 420, protein: 30, carbs: 20, fat: 28, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=chicken+curry+recipe' },
  { title: 'Tomato Soup', description: 'Creamy homemade tomato soup with fresh basil', cuisine: 'American', mealType: 'Lunch', cookingTime: 30, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 180, protein: 6, carbs: 24, fat: 8, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=tomato+soup+recipe' },
  { title: 'Chicken Stir Fry', description: 'Quick chicken stir fry with vegetables and soy sauce', cuisine: 'Chinese', mealType: 'Lunch', cookingTime: 20, servings: 2, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 350, protein: 28, carbs: 22, fat: 18, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=chicken+stir+fry+recipe' },
  { title: 'Chicken Tikka Masala', description: 'Tender chicken in a rich, creamy spiced tomato sauce', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 50, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 460, protein: 34, carbs: 22, fat: 30, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=chicken+tikka+masala+recipe' },
  { title: 'Tomato Basil Pasta', description: 'Simple pasta with fresh tomatoes, garlic, and basil', cuisine: 'Italian', mealType: 'Dinner', cookingTime: 20, servings: 2, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 380, protein: 12, carbs: 52, fat: 14, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=tomato+basil+pasta+recipe' },
  { title: 'Chicken Fried Rice', description: 'Wok-fried rice with chicken, vegetables, and soy sauce', cuisine: 'Chinese', mealType: 'Lunch', cookingTime: 25, servings: 3, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 440, protein: 26, carbs: 48, fat: 18, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=chicken+fried+rice+recipe' },
  { title: 'Onion Tomato Chutney', description: 'Spicy South Indian chutney made with onions and tomatoes', cuisine: 'Indian', mealType: 'Snacks', cookingTime: 15, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 90, protein: 3, carbs: 14, fat: 3, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=onion+tomato+chutney+recipe' },
  { title: 'Chicken Tacos', description: 'Seasoned chicken tacos with fresh tomato salsa and onion', cuisine: 'Mexican', mealType: 'Dinner', cookingTime: 30, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 380, protein: 28, carbs: 32, fat: 16, fiber: 5 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=chicken+tacos+recipe' },
  { title: 'Chicken Soup', description: 'Classic comforting chicken soup with vegetables', cuisine: 'American', mealType: 'Lunch', cookingTime: 45, servings: 6, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 220, protein: 22, carbs: 18, fat: 8, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=chicken+soup+recipe' },
  { title: 'Chicken Shawarma', description: 'Marinated chicken shawarma with tomato and onion salad', cuisine: 'Mediterranean', mealType: 'Dinner', cookingTime: 35, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 410, protein: 32, carbs: 28, fat: 20, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=chicken+shawarma+recipe' },
  { title: 'Chicken Parmesan', description: 'Breaded chicken cutlet with tomato sauce and melted cheese', cuisine: 'Italian', mealType: 'Dinner', cookingTime: 35, servings: 3, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 520, protein: 38, carbs: 30, fat: 26, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=chicken+parmesan+recipe' },
  { title: 'Aloo Paratha', description: 'Crispy Indian flatbread stuffed with spiced potato filling', cuisine: 'Indian', mealType: 'Breakfast', cookingTime: 30, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 290, protein: 7, carbs: 38, fat: 12, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=aloo+paratha+recipe' },
  { title: 'Paneer Butter Masala', description: 'Rich creamy tomato gravy with soft paneer cubes', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 35, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 380, protein: 18, carbs: 16, fat: 28, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=paneer+butter+masala+recipe' },
  { title: 'Aloo Gobi', description: 'Dry Indian curry made with potato and cauliflower florets', cuisine: 'Indian', mealType: 'Lunch', cookingTime: 25, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 180, protein: 5, carbs: 24, fat: 8, fiber: 5 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=aloo+gobi+recipe' },
  { title: 'Palak Paneer', description: 'Creamy spinach curry with paneer cubes and aromatic spices', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 30, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 320, protein: 16, carbs: 12, fat: 24, fiber: 6 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=palak+paneer+recipe' },
  { title: 'Paneer Tikka', description: 'Marinated paneer cubes grilled with peppers and onions', cuisine: 'Indian', mealType: 'Snacks', cookingTime: 25, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 280, protein: 20, carbs: 10, fat: 18, fiber: 2 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=paneer+tikka+recipe' },
  { title: 'Aloo Tikki', description: 'Crispy potato patties served with chutneys and yogurt', cuisine: 'Indian', mealType: 'Snacks', cookingTime: 30, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 240, protein: 4, carbs: 32, fat: 10, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=aloo+tikki+recipe' },
  { title: 'Paneer Bhurji', description: 'Scrambled paneer with onions tomatoes and Indian spices', cuisine: 'Indian', mealType: 'Breakfast', cookingTime: 15, servings: 3, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 260, protein: 18, carbs: 8, fat: 18, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=paneer+bhurji+recipe' },
  { title: 'Matar Paneer', description: 'Green peas cooked in spiced onion tomato gravy with paneer', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 30, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 300, protein: 16, carbs: 18, fat: 20, fiber: 5 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=matar+paneer+recipe' },
  { title: 'Aloo Matar', description: 'Potato and green peas cooked in spiced onion tomato gravy', cuisine: 'Indian', mealType: 'Lunch', cookingTime: 25, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 200, protein: 6, carbs: 28, fat: 8, fiber: 6 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=aloo+matar+recipe' },
  { title: 'Kadai Paneer', description: 'Paneer cooked with bell peppers onions in a kadai masala gravy', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 30, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 340, protein: 18, carbs: 14, fat: 24, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=kadai+paneer+recipe' },
  { title: 'Shahi Paneer', description: 'Royal mughlai paneer in rich creamy saffron infused gravy', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 40, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 400, protein: 16, carbs: 18, fat: 32, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=shahi+paneer+recipe' },
  { title: 'Paneer Korma', description: 'Mild creamy paneer curry with cashew nut base and mild spices', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 35, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 360, protein: 16, carbs: 14, fat: 28, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=paneer+korma+recipe' },
  { title: 'Aloo Jeera', description: 'Simple cumin spiced potato stir fry perfect with roti', cuisine: 'Indian', mealType: 'Lunch', cookingTime: 20, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 160, protein: 3, carbs: 22, fat: 7, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=aloo+jeera+recipe' },
  { title: 'Paneer Masala', description: 'Fried paneer cubes in spicy onion tomato masala gravy', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 30, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 320, protein: 16, carbs: 12, fat: 24, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=paneer+masala+recipe' },
  { title: 'Dahi Aloo', description: 'Potatoes cooked in spiced yogurt gravy with mild herbs', cuisine: 'Indian', mealType: 'Lunch', cookingTime: 25, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 220, protein: 8, carbs: 24, fat: 10, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=dahi+aloo+recipe' },
  { title: 'Pyaz Kebab', description: 'Crispy onion fritters with spices and herbs perfect for tea time', cuisine: 'Indian', mealType: 'Snacks', cookingTime: 20, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 180, protein: 4, carbs: 20, fat: 10, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=pyaz+kebab+recipe' },
  { title: 'Paneer Do Pyaza', description: 'Paneer with double onion preparation in spiced gravy', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 30, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 330, protein: 18, carbs: 14, fat: 22, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=paneer+do+pyaza+recipe' },
  { title: 'Aloo Capsicum', description: 'Potato and bell pepper stir fry with Indian spices', cuisine: 'Indian', mealType: 'Lunch', cookingTime: 20, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 170, protein: 4, carbs: 22, fat: 8, fiber: 5 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=aloo+capsicum+recipe' },
  { title: 'Paneer Jalfrezi', description: 'Paneer stir fried with peppers onions tomatoes in spicy gravy', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 30, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 310, protein: 17, carbs: 14, fat: 22, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=paneer+jalfrezi+recipe' },
  { title: 'Aloo Methi', description: 'Fresh fenugreek leaves cooked with potatoes and spices', cuisine: 'Indian', mealType: 'Lunch', cookingTime: 25, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 150, protein: 5, carbs: 18, fat: 7, fiber: 6 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=aloo+methi+recipe' },
  { title: 'Paneer Lababdar', description: 'Rich tomato based paneer curry with cream and cashews', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 35, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 390, protein: 18, carbs: 16, fat: 30, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=paneer+lababdar+recipe' },
  { title: 'Aloo Baingan', description: 'Potato and eggplant cooked in North Indian style with spices', cuisine: 'Indian', mealType: 'Lunch', cookingTime: 30, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 180, protein: 4, carbs: 22, fat: 9, fiber: 5 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=aloo+baingan+recipe' },
  { title: 'Paneer Pasanda', description: 'Mughlai paneer in creamy almond cashew spiced gravy', cuisine: 'Indian', mealType: 'Dinner', cookingTime: 40, servings: 4, difficulty: 'Hard', nutritionalInfo: JSON.stringify({ calories: 420, protein: 18, carbs: 14, fat: 34, fiber: 3 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=paneer+pasanda+recipe' },
  { title: 'Aloo Palak', description: 'Potatoes cooked with spinach garlic and mild spices', cuisine: 'Indian', mealType: 'Lunch', cookingTime: 25, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 190, protein: 7, carbs: 20, fat: 9, fiber: 6 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=aloo+palak+recipe' },
  { title: 'Paneer 65', description: 'Spicy deep fried paneer coated with chili garlic sauce', cuisine: 'Indian', mealType: 'Snacks', cookingTime: 25, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 340, protein: 16, carbs: 18, fat: 24, fiber: 2 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=paneer+65+recipe' },
  { title: 'Aloo Fry', description: 'Crispy fried potato slices with cumin and chili flakes', cuisine: 'Indian', mealType: 'Snacks', cookingTime: 15, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 200, protein: 3, carbs: 24, fat: 10, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=aloo+fry+recipe' },
  { title: 'Paneer Stuffed Paratha', description: 'Paratha stuffed with spiced paneer and herbs', cuisine: 'Indian', mealType: 'Breakfast', cookingTime: 30, servings: 4, difficulty: 'Medium', nutritionalInfo: JSON.stringify({ calories: 340, protein: 14, carbs: 32, fat: 18, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=paneer+stuffed+paratha+recipe' },
  { title: 'Aloo Onion Bhaji', description: 'Crispy potato onion fritters made with gram flour batter', cuisine: 'Indian', mealType: 'Snacks', cookingTime: 20, servings: 4, difficulty: 'Easy', nutritionalInfo: JSON.stringify({ calories: 220, protein: 6, carbs: 26, fat: 12, fiber: 4 }), image: null, youtubeUrl: 'https://www.youtube.com/results?search_query=aloo+onion+bhaji+recipe' },
];

const recipeIngredients = [
  [{ ingredient: 'Chicken', quantity: '500', unit: 'g' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '4', unit: 'pcs' }, { ingredient: 'Butter', quantity: '50', unit: 'g' }, { ingredient: 'Cream', quantity: '100', unit: 'ml' }, { ingredient: 'Garam Masala', quantity: '2', unit: 'tsp' }, { ingredient: 'Turmeric', quantity: '1', unit: 'tsp' }, { ingredient: 'Garlic', quantity: '4', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Yogurt', quantity: '100', unit: 'ml' }],
  [{ ingredient: 'Pizza Dough', quantity: '250', unit: 'g' }, { ingredient: 'Tomato Sauce', quantity: '100', unit: 'ml' }, { ingredient: 'Mozzarella Cheese', quantity: '150', unit: 'g' }, { ingredient: 'Fresh Basil', quantity: '10', unit: 'pcs' }, { ingredient: 'Olive Oil', quantity: '2', unit: 'tbsp' }, { ingredient: 'Salt', quantity: '1', unit: 'tsp' }],
  [{ ingredient: 'Bell Pepper', quantity: '2', unit: 'pcs' }, { ingredient: 'Broccoli', quantity: '1', unit: 'cup' }, { ingredient: 'Carrot', quantity: '1', unit: 'pcs' }, { ingredient: 'Soy Sauce', quantity: '3', unit: 'tbsp' }, { ingredient: 'Garlic', quantity: '3', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Sesame Oil', quantity: '1', unit: 'tbsp' }, { ingredient: 'Rice', quantity: '1.5', unit: 'cups' }],
  [{ ingredient: 'Banana', quantity: '2', unit: 'pcs' }, { ingredient: 'Eggs', quantity: '2', unit: 'pcs' }, { ingredient: 'Flour', quantity: '1', unit: 'cup' }, { ingredient: 'Milk', quantity: '0.5', unit: 'cup' }, { ingredient: 'Baking Powder', quantity: '1', unit: 'tsp' }, { ingredient: 'Butter', quantity: '2', unit: 'tbsp' }, { ingredient: 'Honey', quantity: '2', unit: 'tbsp' }],
  [{ ingredient: 'Romaine Lettuce', quantity: '1', unit: 'head' }, { ingredient: 'Parmesan Cheese', quantity: '50', unit: 'g' }, { ingredient: 'Bread', quantity: '2', unit: 'slices' }, { ingredient: 'Garlic', quantity: '1', unit: 'pcs' }, { ingredient: 'Lemon', quantity: '1', unit: 'pcs' }, { ingredient: 'Olive Oil', quantity: '3', unit: 'tbsp' }, { ingredient: 'Anchovy Paste', quantity: '1', unit: 'tsp' }, { ingredient: 'Egg Yolk', quantity: '1', unit: 'pcs' }],
  [{ ingredient: 'Rice', quantity: '2', unit: 'cups' }, { ingredient: 'Urad Dal', quantity: '0.5', unit: 'cup' }, { ingredient: 'Potato', quantity: '4', unit: 'pcs' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Mustard Seeds', quantity: '1', unit: 'tsp' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Green Chili', quantity: '2', unit: 'pcs' }, { ingredient: 'Curry Leaves', quantity: '10', unit: 'pcs' }],
  [{ ingredient: 'Dark Chocolate', quantity: '200', unit: 'g' }, { ingredient: 'Eggs', quantity: '4', unit: 'pcs' }, { ingredient: 'Sugar', quantity: '50', unit: 'g' }, { ingredient: 'Cream', quantity: '200', unit: 'ml' }, { ingredient: 'Vanilla Extract', quantity: '1', unit: 'tsp' }],
  [{ ingredient: 'Basmati Rice', quantity: '3', unit: 'cups' }, { ingredient: 'Chicken', quantity: '750', unit: 'g' }, { ingredient: 'Onion', quantity: '3', unit: 'pcs' }, { ingredient: 'Yogurt', quantity: '1', unit: 'cup' }, { ingredient: 'Biryani Masala', quantity: '3', unit: 'tbsp' }, { ingredient: 'Saffron', quantity: '1', unit: 'tsp' }, { ingredient: 'Milk', quantity: '0.5', unit: 'cup' }, { ingredient: 'Ghee', quantity: '4', unit: 'tbsp' }, { ingredient: 'Fresh Mint', quantity: '0.5', unit: 'cup' }, { ingredient: 'Garlic', quantity: '6', unit: 'pcs' }],
  [{ ingredient: 'Cucumber', quantity: '1', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '3', unit: 'pcs' }, { ingredient: 'Red Onion', quantity: '0.5', unit: 'pcs' }, { ingredient: 'Feta Cheese', quantity: '100', unit: 'g' }, { ingredient: 'Kalamata Olives', quantity: '50', unit: 'g' }, { ingredient: 'Olive Oil', quantity: '3', unit: 'tbsp' }, { ingredient: 'Oregano', quantity: '1', unit: 'tsp' }],
  [{ ingredient: 'Spaghetti', quantity: '300', unit: 'g' }, { ingredient: 'Bacon', quantity: '150', unit: 'g' }, { ingredient: 'Eggs', quantity: '3', unit: 'pcs' }, { ingredient: 'Parmesan Cheese', quantity: '80', unit: 'g' }, { ingredient: 'Black Pepper', quantity: '1', unit: 'tsp' }, { ingredient: 'Garlic', quantity: '2', unit: 'pcs' }, { ingredient: 'Salt', quantity: '1', unit: 'tsp' }],
  [{ ingredient: 'Chicken', quantity: '500', unit: 'g' }, { ingredient: 'Tomato', quantity: '3', unit: 'pcs' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Curry Powder', quantity: '2', unit: 'tbsp' }, { ingredient: 'Coconut Milk', quantity: '400', unit: 'ml' }, { ingredient: 'Garlic', quantity: '4', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Tomato', quantity: '6', unit: 'pcs' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Garlic', quantity: '3', unit: 'pcs' }, { ingredient: 'Olive Oil', quantity: '2', unit: 'tbsp' }, { ingredient: 'Fresh Basil', quantity: '10', unit: 'pcs' }, { ingredient: 'Salt', quantity: '1', unit: 'tsp' }, { ingredient: 'Sugar', quantity: '1', unit: 'tsp' }],
  [{ ingredient: 'Chicken', quantity: '400', unit: 'g' }, { ingredient: 'Bell Pepper', quantity: '2', unit: 'pcs' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Soy Sauce', quantity: '3', unit: 'tbsp' }, { ingredient: 'Garlic', quantity: '3', unit: 'pcs' }, { ingredient: 'Sesame Oil', quantity: '1', unit: 'tbsp' }, { ingredient: 'Rice', quantity: '2', unit: 'cups' }],
  [{ ingredient: 'Chicken', quantity: '600', unit: 'g' }, { ingredient: 'Tomato', quantity: '4', unit: 'pcs' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Cream', quantity: '100', unit: 'ml' }, { ingredient: 'Garam Masala', quantity: '2', unit: 'tsp' }, { ingredient: 'Turmeric', quantity: '1', unit: 'tsp' }, { ingredient: 'Garlic', quantity: '5', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Yogurt', quantity: '100', unit: 'ml' }],
  [{ ingredient: 'Spaghetti', quantity: '300', unit: 'g' }, { ingredient: 'Tomato', quantity: '4', unit: 'pcs' }, { ingredient: 'Garlic', quantity: '4', unit: 'pcs' }, { ingredient: 'Fresh Basil', quantity: '15', unit: 'pcs' }, { ingredient: 'Olive Oil', quantity: '3', unit: 'tbsp' }, { ingredient: 'Parmesan Cheese', quantity: '50', unit: 'g' }, { ingredient: 'Salt', quantity: '1', unit: 'tsp' }],
  [{ ingredient: 'Chicken', quantity: '300', unit: 'g' }, { ingredient: 'Rice', quantity: '3', unit: 'cups' }, { ingredient: 'Eggs', quantity: '2', unit: 'pcs' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Bell Pepper', quantity: '1', unit: 'pcs' }, { ingredient: 'Soy Sauce', quantity: '3', unit: 'tbsp' }, { ingredient: 'Sesame Oil', quantity: '1', unit: 'tbsp' }, { ingredient: 'Garlic', quantity: '3', unit: 'pcs' }],
  [{ ingredient: 'Onion', quantity: '3', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '2', unit: 'pcs' }, { ingredient: 'Green Chili', quantity: '3', unit: 'pcs' }, { ingredient: 'Garlic', quantity: '4', unit: 'pcs' }, { ingredient: 'Coconut Oil', quantity: '2', unit: 'tbsp' }, { ingredient: 'Mustard Seeds', quantity: '1', unit: 'tsp' }, { ingredient: 'Curry Leaves', quantity: '10', unit: 'pcs' }],
  [{ ingredient: 'Chicken', quantity: '500', unit: 'g' }, { ingredient: 'Tomato', quantity: '2', unit: 'pcs' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Taco Shells', quantity: '8', unit: 'pcs' }, { ingredient: 'Cumin', quantity: '1', unit: 'tsp' }, { ingredient: 'Paprika', quantity: '1', unit: 'tsp' }, { ingredient: 'Lettuce', quantity: '1', unit: 'cup' }, { ingredient: 'Cheese', quantity: '100', unit: 'g' }],
  [{ ingredient: 'Chicken', quantity: '400', unit: 'g' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Carrot', quantity: '2', unit: 'pcs' }, { ingredient: 'Celery', quantity: '2', unit: 'stalks' }, { ingredient: 'Garlic', quantity: '3', unit: 'pcs' }, { ingredient: 'Noodles', quantity: '200', unit: 'g' }, { ingredient: 'Chicken Broth', quantity: '1', unit: 'liter' }],
  [{ ingredient: 'Chicken', quantity: '500', unit: 'g' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '2', unit: 'pcs' }, { ingredient: 'Yogurt', quantity: '100', unit: 'ml' }, { ingredient: 'Shawarma Spice', quantity: '2', unit: 'tbsp' }, { ingredient: 'Garlic', quantity: '4', unit: 'pcs' }, { ingredient: 'Pita Bread', quantity: '4', unit: 'pcs' }],
  [{ ingredient: 'Chicken Breast', quantity: '400', unit: 'g' }, { ingredient: 'Tomato', quantity: '3', unit: 'pcs' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Parmesan Cheese', quantity: '80', unit: 'g' }, { ingredient: 'Breadcrumbs', quantity: '1', unit: 'cup' }, { ingredient: 'Eggs', quantity: '2', unit: 'pcs' }, { ingredient: 'Flour', quantity: '1', unit: 'cup' }],
  [{ ingredient: 'Potato', quantity: '4', unit: 'pcs' }, { ingredient: 'Wheat Flour', quantity: '2', unit: 'cups' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Green Chili', quantity: '2', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Coriander Leaves', quantity: '2', unit: 'tbsp' }, { ingredient: 'Yogurt', quantity: '2', unit: 'tbsp' }, { ingredient: 'Ghee', quantity: '4', unit: 'tbsp' }, { ingredient: 'Salt', quantity: '1', unit: 'tsp' }],
  [{ ingredient: 'Paneer', quantity: '300', unit: 'g' }, { ingredient: 'Tomato', quantity: '4', unit: 'pcs' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Butter', quantity: '50', unit: 'g' }, { ingredient: 'Cream', quantity: '100', unit: 'ml' }, { ingredient: 'Garam Masala', quantity: '1', unit: 'tsp' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Garlic', quantity: '4', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Kashmiri Chili', quantity: '2', unit: 'tsp' }],
  [{ ingredient: 'Potato', quantity: '3', unit: 'pcs' }, { ingredient: 'Cauliflower', quantity: '2', unit: 'cups' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Cumin Seeds', quantity: '1', unit: 'tsp' }, { ingredient: 'Coriander Powder', quantity: '1', unit: 'tsp' }, { ingredient: 'Green Chili', quantity: '2', unit: 'pcs' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '250', unit: 'g' }, { ingredient: 'Spinach', quantity: '500', unit: 'g' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Garlic', quantity: '4', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Green Chili', quantity: '2', unit: 'pcs' }, { ingredient: 'Cream', quantity: '2', unit: 'tbsp' }, { ingredient: 'Cumin', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Ghee', quantity: '2', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '300', unit: 'g' }, { ingredient: 'Bell Pepper', quantity: '2', unit: 'pcs' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Yogurt', quantity: '100', unit: 'ml' }, { ingredient: 'Garam Masala', quantity: '1', unit: 'tsp' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Kashmiri Chili', quantity: '2', unit: 'tsp' }, { ingredient: 'Lemon Juice', quantity: '1', unit: 'tbsp' }],
  [{ ingredient: 'Potato', quantity: '4', unit: 'pcs' }, { ingredient: 'Gram Flour', quantity: '1', unit: 'cup' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Green Chili', quantity: '2', unit: 'pcs' }, { ingredient: 'Coriander Powder', quantity: '1', unit: 'tsp' }, { ingredient: 'Cumin Powder', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Yogurt', quantity: '2', unit: 'tbsp' }, { ingredient: 'Oil', quantity: '4', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '250', unit: 'g' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '2', unit: 'pcs' }, { ingredient: 'Green Chili', quantity: '2', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Garam Masala', quantity: '1', unit: 'tsp' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }, { ingredient: 'Coriander Leaves', quantity: '1', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '200', unit: 'g' }, { ingredient: 'Green Peas', quantity: '1', unit: 'cup' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '2', unit: 'pcs' }, { ingredient: 'Cream', quantity: '3', unit: 'tbsp' }, { ingredient: 'Garam Masala', quantity: '1', unit: 'tsp' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Potato', quantity: '3', unit: 'pcs' }, { ingredient: 'Green Peas', quantity: '1', unit: 'cup' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '1', unit: 'pcs' }, { ingredient: 'Cumin', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Coriander Powder', quantity: '1', unit: 'tsp' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '300', unit: 'g' }, { ingredient: 'Bell Pepper', quantity: '2', unit: 'pcs' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '2', unit: 'pcs' }, { ingredient: 'Kadai Masala', quantity: '2', unit: 'tsp' }, { ingredient: 'Garlic', quantity: '3', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '300', unit: 'g' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '3', unit: 'pcs' }, { ingredient: 'Cream', quantity: '100', unit: 'ml' }, { ingredient: 'Cashew Paste', quantity: '3', unit: 'tbsp' }, { ingredient: 'Saffron', quantity: '1', unit: 'tsp' }, { ingredient: 'Garam Masala', quantity: '1', unit: 'tsp' }, { ingredient: 'Butter', quantity: '30', unit: 'g' }],
  [{ ingredient: 'Paneer', quantity: '250', unit: 'g' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '2', unit: 'pcs' }, { ingredient: 'Cream', quantity: '50', unit: 'ml' }, { ingredient: 'Cashew Paste', quantity: '2', unit: 'tbsp' }, { ingredient: 'Kashmiri Chili', quantity: '2', unit: 'tsp' }, { ingredient: 'Garam Masala', quantity: '1', unit: 'tsp' }, { ingredient: 'Butter', quantity: '30', unit: 'g' }],
  [{ ingredient: 'Potato', quantity: '4', unit: 'pcs' }, { ingredient: 'Cumin Seeds', quantity: '1', unit: 'tsp' }, { ingredient: 'Green Chili', quantity: '2', unit: 'pcs' }, { ingredient: 'Coriander Leaves', quantity: '1', unit: 'tbsp' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '300', unit: 'g' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '3', unit: 'pcs' }, { ingredient: 'Garam Masala', quantity: '1', unit: 'tsp' }, { ingredient: 'Kashmiri Chili', quantity: '2', unit: 'tsp' }, { ingredient: 'Garlic', quantity: '3', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Potato', quantity: '3', unit: 'pcs' }, { ingredient: 'Yogurt', quantity: '1', unit: 'cup' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Green Chili', quantity: '2', unit: 'pcs' }, { ingredient: 'Coriander Leaves', quantity: '1', unit: 'tbsp' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Cumin', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Onion', quantity: '4', unit: 'pcs' }, { ingredient: 'Gram Flour', quantity: '0.5', unit: 'cup' }, { ingredient: 'Green Chili', quantity: '3', unit: 'pcs' }, { ingredient: 'Coriander Leaves', quantity: '2', unit: 'tbsp' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Cumin Seeds', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Salt', quantity: '1', unit: 'tsp' }, { ingredient: 'Oil', quantity: '4', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '200', unit: 'g' }, { ingredient: 'Potato', quantity: '2', unit: 'pcs' }, { ingredient: 'Wheat Flour', quantity: '1.5', unit: 'cups' }, { ingredient: 'Coriander Leaves', quantity: '2', unit: 'tbsp' }, { ingredient: 'Green Chili', quantity: '2', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Ghee', quantity: '4', unit: 'tbsp' }, { ingredient: 'Yogurt', quantity: '2', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '250', unit: 'g' }, { ingredient: 'Onion', quantity: '3', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '2', unit: 'pcs' }, { ingredient: 'Cream', quantity: '50', unit: 'ml' }, { ingredient: 'Garam Masala', quantity: '1', unit: 'tsp' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Garlic', quantity: '3', unit: 'pcs' }, { ingredient: 'Butter', quantity: '30', unit: 'g' }],
  [{ ingredient: 'Potato', quantity: '2', unit: 'pcs' }, { ingredient: 'Bell Pepper', quantity: '1', unit: 'pcs' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Cumin', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Coriander Powder', quantity: '1', unit: 'tsp' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '300', unit: 'g' }, { ingredient: 'Bell Pepper', quantity: '2', unit: 'pcs' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '2', unit: 'pcs' }, { ingredient: 'Tomato Sauce', quantity: '3', unit: 'tbsp' }, { ingredient: 'Garlic', quantity: '3', unit: 'pcs' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }, { ingredient: 'Garam Masala', quantity: '1', unit: 'tsp' }],
  [{ ingredient: 'Potato', quantity: '3', unit: 'pcs' }, { ingredient: 'Fenugreek Leaves', quantity: '2', unit: 'cups' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Garlic', quantity: '3', unit: 'pcs' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Cumin', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '300', unit: 'g' }, { ingredient: 'Tomato', quantity: '4', unit: 'pcs' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Cream', quantity: '100', unit: 'ml' }, { ingredient: 'Cashew Paste', quantity: '3', unit: 'tbsp' }, { ingredient: 'Garam Masala', quantity: '1', unit: 'tsp' }, { ingredient: 'Butter', quantity: '40', unit: 'g' }, { ingredient: 'Garlic', quantity: '4', unit: 'pcs' }],
  [{ ingredient: 'Potato', quantity: '3', unit: 'pcs' }, { ingredient: 'Eggplant', quantity: '1', unit: 'pcs' }, { ingredient: 'Onion', quantity: '1', unit: 'pcs' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Cumin', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Coriander Powder', quantity: '1', unit: 'tsp' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '300', unit: 'g' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Tomato', quantity: '3', unit: 'pcs' }, { ingredient: 'Cream', quantity: '100', unit: 'ml' }, { ingredient: 'Almond Paste', quantity: '2', unit: 'tbsp' }, { ingredient: 'Cashew Paste', quantity: '2', unit: 'tbsp' }, { ingredient: 'Saffron', quantity: '1', unit: 'tsp' }, { ingredient: 'Ghee', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Potato', quantity: '3', unit: 'pcs' }, { ingredient: 'Spinach', quantity: '300', unit: 'g' }, { ingredient: 'Garlic', quantity: '4', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Green Chili', quantity: '2', unit: 'pcs' }, { ingredient: 'Turmeric', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Oil', quantity: '3', unit: 'tbsp' }],
  [{ ingredient: 'Paneer', quantity: '300', unit: 'g' }, { ingredient: 'All Purpose Flour', quantity: '1', unit: 'cup' }, { ingredient: 'Corn Flour', quantity: '2', unit: 'tbsp' }, { ingredient: 'Green Chili', quantity: '3', unit: 'pcs' }, { ingredient: 'Garlic', quantity: '4', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Soy Sauce', quantity: '1', unit: 'tbsp' }, { ingredient: 'Oil', quantity: '1', unit: 'cup' }],
  [{ ingredient: 'Potato', quantity: '3', unit: 'pcs' }, { ingredient: 'Cumin Seeds', quantity: '1', unit: 'tsp' }, { ingredient: 'Red Chili Flakes', quantity: '1', unit: 'tsp' }, { ingredient: 'Coriander Leaves', quantity: '1', unit: 'tbsp' }, { ingredient: 'Oil', quantity: '4', unit: 'tbsp' }, { ingredient: 'Salt', quantity: '1', unit: 'tsp' }],
  [{ ingredient: 'Paneer', quantity: '200', unit: 'g' }, { ingredient: 'Potato', quantity: '2', unit: 'pcs' }, { ingredient: 'Wheat Flour', quantity: '1.5', unit: 'cups' }, { ingredient: 'Coriander Leaves', quantity: '2', unit: 'tbsp' }, { ingredient: 'Green Chili', quantity: '2', unit: 'pcs' }, { ingredient: 'Ginger', quantity: '1', unit: 'inch' }, { ingredient: 'Ghee', quantity: '4', unit: 'tbsp' }, { ingredient: 'Butter', quantity: '2', unit: 'tbsp' }],
  [{ ingredient: 'Potato', quantity: '3', unit: 'pcs' }, { ingredient: 'Onion', quantity: '2', unit: 'pcs' }, { ingredient: 'Gram Flour', quantity: '1', unit: 'cup' }, { ingredient: 'Green Chili', quantity: '3', unit: 'pcs' }, { ingredient: 'Coriander Powder', quantity: '1', unit: 'tsp' }, { ingredient: 'Cumin Powder', quantity: '0.5', unit: 'tsp' }, { ingredient: 'Oil', quantity: '4', unit: 'tbsp' }],
];

const recipeSteps = [
  [{ stepNumber: 1, instruction: 'Marinate chicken with yogurt, turmeric, and garam masala for 30 minutes', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Heat butter in a pan, saute onions until golden brown', estimatedTime: 8 }, { stepNumber: 3, instruction: 'Add garlic, ginger, and tomatoes. Cook until tomatoes soften', estimatedTime: 10 }, { stepNumber: 4, instruction: 'Add marinated chicken and cook until done', estimatedTime: 15 }, { stepNumber: 5, instruction: 'Stir in cream and simmer for 5 minutes', estimatedTime: 5 }, { stepNumber: 6, instruction: 'Serve hot with rice or naan bread', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Preheat oven to 250C with pizza stone or baking tray', estimatedTime: 10 }, { stepNumber: 2, instruction: 'Roll out pizza dough on a floured surface', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Spread tomato sauce evenly over the dough', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Add torn mozzarella pieces on top', estimatedTime: 2 }, { stepNumber: 5, instruction: 'Drizzle with olive oil and bake for 12-15 minutes', estimatedTime: 15 }, { stepNumber: 6, instruction: 'Top with fresh basil leaves and serve', estimatedTime: 1 }],
  [{ stepNumber: 1, instruction: 'Cook rice according to package instructions', estimatedTime: 15 }, { stepNumber: 2, instruction: 'Cut all vegetables into bite-sized pieces', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Heat sesame oil in a wok over high heat', estimatedTime: 2 }, { stepNumber: 4, instruction: 'Add garlic and ginger, stir fry for 30 seconds', estimatedTime: 1 }, { stepNumber: 5, instruction: 'Add vegetables and stir fry for 3-4 minutes', estimatedTime: 4 }, { stepNumber: 6, instruction: 'Add soy sauce and toss everything together', estimatedTime: 1 }, { stepNumber: 7, instruction: 'Serve over rice', estimatedTime: 1 }],
  [{ stepNumber: 1, instruction: 'Mash bananas in a bowl until smooth', estimatedTime: 2 }, { stepNumber: 2, instruction: 'Add eggs, milk, and melted butter, mix well', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Add flour and baking powder, stir until just combined', estimatedTime: 2 }, { stepNumber: 4, instruction: 'Heat a non-stick pan over medium heat with butter', estimatedTime: 3 }, { stepNumber: 5, instruction: 'Pour 1/4 cup batter per pancake, cook until bubbles form', estimatedTime: 5 }, { stepNumber: 6, instruction: 'Flip and cook for another 2 minutes', estimatedTime: 3 }, { stepNumber: 7, instruction: 'Serve with honey, fresh fruit, or maple syrup', estimatedTime: 1 }],
  [{ stepNumber: 1, instruction: 'Cut bread into cubes and toast in oven at 180C for 10 minutes', estimatedTime: 10 }, { stepNumber: 2, instruction: 'Make dressing: mix egg yolk, garlic, lemon juice, anchovy paste, and olive oil', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Wash and chop romaine lettuce', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Toss lettuce with dressing', estimatedTime: 2 }, { stepNumber: 5, instruction: 'Top with croutons and shaved parmesan', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Soak rice and urad dal separately for 4 hours', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Grind both into smooth batter and ferment overnight', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Boil and mash potatoes for the filling', estimatedTime: 15 }, { stepNumber: 4, instruction: 'Temper mustard seeds, curry leaves, onions, and chili. Mix with potatoes', estimatedTime: 5 }, { stepNumber: 5, instruction: 'Spread batter thinly on hot griddle, cook until crispy', estimatedTime: 10 }, { stepNumber: 6, instruction: 'Place potato filling in center, fold and serve with chutney', estimatedTime: 3 }],
  [{ stepNumber: 1, instruction: 'Melt chocolate over a double boiler and let cool slightly', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Separate egg yolks from whites', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Whip cream and egg yolks with sugar until fluffy', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Fold melted chocolate into cream mixture', estimatedTime: 2 }, { stepNumber: 5, instruction: 'Whip egg whites to stiff peaks, fold into chocolate mixture', estimatedTime: 3 }, { stepNumber: 6, instruction: 'Refrigerate for at least 2 hours before serving', estimatedTime: 120 }],
  [{ stepNumber: 1, instruction: 'Marinate chicken with yogurt, biryani masala, and garlic for 30 minutes', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Fry sliced onions until golden and crispy', estimatedTime: 10 }, { stepNumber: 3, instruction: 'Cook basmati rice until 70% done, drain and set aside', estimatedTime: 15 }, { stepNumber: 4, instruction: 'Cook marinated chicken in ghee until done', estimatedTime: 15 }, { stepNumber: 5, instruction: 'Layer chicken and rice in a heavy-bottomed pot', estimatedTime: 5 }, { stepNumber: 6, instruction: 'Add saffron milk, mint, and fried onions. Seal and cook on low heat', estimatedTime: 20 }, { stepNumber: 7, instruction: 'Serve hot with raita and boiled eggs', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Chop cucumber, tomatoes, and red onion into chunks', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Combine vegetables in a large bowl', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Add olives and crumbled feta cheese', estimatedTime: 2 }, { stepNumber: 4, instruction: 'Drizzle with olive oil and sprinkle oregano', estimatedTime: 1 }, { stepNumber: 5, instruction: 'Toss gently and serve immediately', estimatedTime: 1 }],
  [{ stepNumber: 1, instruction: 'Cook spaghetti in salted boiling water until al dente', estimatedTime: 10 }, { stepNumber: 2, instruction: 'Fry bacon with garlic until crispy', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Mix eggs with grated parmesan and black pepper', estimatedTime: 2 }, { stepNumber: 4, instruction: 'Drain pasta, reserving some pasta water', estimatedTime: 1 }, { stepNumber: 5, instruction: 'Toss hot pasta with bacon, then add egg mixture off heat', estimatedTime: 2 }, { stepNumber: 6, instruction: 'Add pasta water as needed for creamy consistency', estimatedTime: 1 }, { stepNumber: 7, instruction: 'Serve immediately with extra parmesan', estimatedTime: 1 }],
  [{ stepNumber: 1, instruction: 'Cut chicken into bite-sized pieces and marinate with curry powder', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Heat oil in a pot, saute onions until translucent', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Add garlic, ginger, and tomatoes. Cook until soft', estimatedTime: 10 }, { stepNumber: 4, instruction: 'Add chicken and cook for 10 minutes', estimatedTime: 10 }, { stepNumber: 5, instruction: 'Pour in coconut milk and simmer for 20 minutes', estimatedTime: 20 }, { stepNumber: 6, instruction: 'Serve with rice or bread', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Blanch tomatoes in boiling water for 2 minutes, then peel and chop', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Saute onions and garlic in olive oil until soft', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Add chopped tomatoes and cook for 15 minutes', estimatedTime: 15 }, { stepNumber: 4, instruction: 'Blend until smooth with an immersion blender', estimatedTime: 3 }, { stepNumber: 5, instruction: 'Stir in fresh basil, salt, and a pinch of sugar', estimatedTime: 1 }, { stepNumber: 6, instruction: 'Serve hot with crusty bread', estimatedTime: 1 }],
  [{ stepNumber: 1, instruction: 'Cut chicken into strips and season with salt and pepper', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Heat sesame oil in a wok over high heat', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Stir fry chicken for 5 minutes until cooked', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Add bell peppers, onion, and garlic, stir fry for 3 minutes', estimatedTime: 3 }, { stepNumber: 5, instruction: 'Add soy sauce and toss for 1 minute', estimatedTime: 1 }, { stepNumber: 6, instruction: 'Serve over steamed rice', estimatedTime: 1 }],
  [{ stepNumber: 1, instruction: 'Marinate chicken in yogurt and garam masala for 30 minutes', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Heat oil in a pan, cook chicken until golden', estimatedTime: 10 }, { stepNumber: 3, instruction: 'Saute onions and garlic until soft', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Add tomatoes and cook until mushy', estimatedTime: 10 }, { stepNumber: 5, instruction: 'Add cream and simmer for 10 minutes', estimatedTime: 10 }, { stepNumber: 6, instruction: 'Serve with naan or rice', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cook spaghetti in salted boiling water until al dente', estimatedTime: 10 }, { stepNumber: 2, instruction: 'Dice tomatoes and mince garlic', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Saute garlic in olive oil until fragrant', estimatedTime: 2 }, { stepNumber: 4, instruction: 'Add tomatoes and cook until they break down', estimatedTime: 8 }, { stepNumber: 5, instruction: 'Toss pasta with sauce, top with basil and parmesan', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cook rice and let it cool completely', estimatedTime: 15 }, { stepNumber: 2, instruction: 'Cut chicken into small pieces and season', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Heat oil in a wok over high heat', estimatedTime: 2 }, { stepNumber: 4, instruction: 'Stir fry chicken until cooked through', estimatedTime: 5 }, { stepNumber: 5, instruction: 'Add onion, bell pepper, and garlic', estimatedTime: 2 }, { stepNumber: 6, instruction: 'Add rice and soy sauce, stir fry for 3 minutes', estimatedTime: 3 }, { stepNumber: 7, instruction: 'Scramble eggs in the wok and mix in', estimatedTime: 2 }, { stepNumber: 8, instruction: 'Serve hot', estimatedTime: 1 }],
  [{ stepNumber: 1, instruction: 'Chop onions and tomatoes finely', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Heat coconut oil in a pan', estimatedTime: 1 }, { stepNumber: 3, instruction: 'Temper mustard seeds and curry leaves', estimatedTime: 1 }, { stepNumber: 4, instruction: 'Saute onions until golden brown', estimatedTime: 8 }, { stepNumber: 5, instruction: 'Add tomatoes, green chili, and garlic', estimatedTime: 5 }, { stepNumber: 6, instruction: 'Cook until oil separates, then cool and grind to a paste', estimatedTime: 10 }],
  [{ stepNumber: 1, instruction: 'Season chicken with cumin, paprika, salt, and pepper', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Cook chicken in a hot pan until done', estimatedTime: 10 }, { stepNumber: 3, instruction: 'Dice tomato and onion for salsa', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Warm taco shells in the oven', estimatedTime: 2 }, { stepNumber: 5, instruction: 'Fill shells with chicken, salsa, lettuce, and cheese', estimatedTime: 3 }],
  [{ stepNumber: 1, instruction: 'Cut chicken into cubes and dice vegetables', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Heat oil in a large pot', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Brown chicken on all sides', estimatedTime: 8 }, { stepNumber: 4, instruction: 'Add onion, carrot, celery, and garlic', estimatedTime: 5 }, { stepNumber: 5, instruction: 'Pour in chicken broth and bring to a boil', estimatedTime: 3 }, { stepNumber: 6, instruction: 'Add noodles and simmer for 15 minutes', estimatedTime: 15 }, { stepNumber: 7, instruction: 'Season and serve hot', estimatedTime: 1 }],
  [{ stepNumber: 1, instruction: 'Marinate chicken in yogurt and shawarma spice for 30 minutes', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Cook chicken in a hot pan until charred and done', estimatedTime: 10 }, { stepNumber: 3, instruction: 'Make salad: dice tomato and onion', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Warm pita bread', estimatedTime: 2 }, { stepNumber: 5, instruction: 'Slice chicken and place in pita with salad and garlic sauce', estimatedTime: 3 }],
  [{ stepNumber: 1, instruction: 'Pound chicken breast to even thickness', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Dredge in flour, dip in beaten eggs, coat in breadcrumbs', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Fry chicken until golden and cooked through', estimatedTime: 8 }, { stepNumber: 4, instruction: 'Make tomato sauce with garlic and herbs', estimatedTime: 5 }, { stepNumber: 5, instruction: 'Place chicken on baking tray, top with sauce and parmesan', estimatedTime: 2 }, { stepNumber: 6, instruction: 'Bake at 200C for 15 minutes until cheese is bubbly', estimatedTime: 15 }],
  [{ stepNumber: 1, instruction: 'Peel and cube potatoes', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Make dough by mixing wheat flour, water, salt, and yogurt', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Prepare stuffing by mashing boiled potatoes with green chili, ginger, coriander, and spices', estimatedTime: 10 }, { stepNumber: 4, instruction: 'Divide dough and stuffing into equal portions', estimatedTime: 3 }, { stepNumber: 5, instruction: 'Roll each portion flat, stuff with potato mixture, and seal edges', estimatedTime: 5 }, { stepNumber: 6, instruction: 'Cook on tawa with ghee until both sides are golden brown', estimatedTime: 10 }, { stepNumber: 7, instruction: 'Serve hot with butter, yogurt, and pickle', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Dice paneer into cubes', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Blend tomatoes into a smooth puree', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Melt butter in a pan and saute onions until golden', estimatedTime: 8 }, { stepNumber: 4, instruction: 'Add garlic, ginger, and tomato puree. Cook until oil separates', estimatedTime: 10 }, { stepNumber: 5, instruction: 'Add garam masala, turmeric, and kashmiri chili powder', estimatedTime: 2 }, { stepNumber: 6, instruction: 'Pour in cream and add paneer cubes. Simmer for 10 minutes', estimatedTime: 10 }, { stepNumber: 7, instruction: 'Garnish with cream and serve hot with rice or naan', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut potatoes into cubes and cauliflower into florets', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Heat oil in a pan and add cumin seeds', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Add turmeric, green chili, and onion. Cook for 3 minutes', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Add potatoes, cauliflower, coriander powder, and salt', estimatedTime: 2 }, { stepNumber: 5, instruction: 'Cover and cook on medium heat for 15 minutes, stirring occasionally', estimatedTime: 15 }, { stepNumber: 6, instruction: 'Garnish with coriander leaves and serve with roti', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Clean and wash spinach thoroughly', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Blanch spinach in boiling water for 2 minutes, then blend into a smooth paste', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Heat ghee in a pan and saute cumin, minced garlic, ginger, and green chili', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Add spinach paste and cook for 8 minutes, stirring occasionally', estimatedTime: 8 }, { stepNumber: 5, instruction: 'Add diced paneer and cream. Cook for 5 more minutes', estimatedTime: 5 }, { stepNumber: 6, instruction: 'Season with salt and serve hot with rice or roti', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut paneer into cubes and marinate with yogurt and spices for 15 minutes', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Thread paneer and bell peppers onto skewers alternately', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Grill in oven at 220C for 10 minutes, turning once', estimatedTime: 10 }, { stepNumber: 4, instruction: 'Serve hot with mint chutney and onion rings', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Boil and peel potatoes, then grate them', estimatedTime: 10 }, { stepNumber: 2, instruction: 'Mix grated potato with gram flour, green chili, coriander powder, and cumin', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Add yogurt and salt to form a thick dough', estimatedTime: 2 }, { stepNumber: 4, instruction: 'Shape into round patties', estimatedTime: 5 }, { stepNumber: 5, instruction: 'Deep fry in hot oil until golden brown on both sides', estimatedTime: 8 }, { stepNumber: 6, instruction: 'Serve hot with tamarind chutney and yogurt', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut paneer into small cubes', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Heat oil in a pan and saute finely chopped onions until translucent', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Add ginger, garlic, green chili, and tomato. Cook until soft', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Add garam masala and cook for 1 minute', estimatedTime: 1 }, { stepNumber: 5, instruction: 'Add paneer cubes, toss well, and cook for 3 minutes', estimatedTime: 3 }, { stepNumber: 6, instruction: 'Garnish with coriander leaves and serve with roti or paratha', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Boil potatoes and green peas separately', estimatedTime: 10 }, { stepNumber: 2, instruction: 'Heat oil and saute chopped onions until golden', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Add tomatoes and cook until they break down', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Add garam masala, turmeric, and coriander powder', estimatedTime: 2 }, { stepNumber: 5, instruction: 'Add boiled potatoes, peas, and cream. Simmer for 10 minutes', estimatedTime: 10 }, { stepNumber: 6, instruction: 'Serve hot with jeera rice or roti', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Boil potatoes and green peas', estimatedTime: 10 }, { stepNumber: 2, instruction: 'Heat oil and add cumin seeds, turmeric, and coriander powder', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Add chopped onion, tomato, and green chili. Cook for 5 minutes', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Add boiled potatoes and peas, toss well', estimatedTime: 3 }, { stepNumber: 5, instruction: 'Cook for 5 more minutes and garnish with coriander', estimatedTime: 5 }, { stepNumber: 6, instruction: 'Serve with roti or paratha', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut paneer into cubes and bell peppers into strips', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Heat oil in a kadai and saute onions, garlic, and ginger', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Add tomatoes and kadai masala. Cook until oil separates', estimatedTime: 8 }, { stepNumber: 4, instruction: 'Add bell peppers and paneer. Toss for 3 minutes', estimatedTime: 3 }, { stepNumber: 5, instruction: 'Cook on high heat for 2 minutes and serve hot', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut paneer into squares', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Blend onions and tomatoes into a smooth puree', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Heat butter and saute cashew paste until golden', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Add onion-tomato puree, garam masala, and cook until oil separates', estimatedTime: 10 }, { stepNumber: 5, instruction: 'Add cream, saffron, and paneer. Cook for 8 minutes on low heat', estimatedTime: 8 }, { stepNumber: 6, instruction: 'Garnish with saffron cream and serve with naan', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut paneer into cubes', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Heat butter and saute onions until soft', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Add tomatoes, cashew paste, kashmiri chili, and garam masala', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Cook until oil separates from the masala', estimatedTime: 8 }, { stepNumber: 5, instruction: 'Add paneer and cream. Simmer for 10 minutes', estimatedTime: 10 }, { stepNumber: 6, instruction: 'Serve hot with jeera rice or naan', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Peel and cube potatoes', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Heat oil and add cumin seeds and turmeric', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Add potatoes and green chili. Toss well', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Cover and cook on low heat for 15 minutes', estimatedTime: 15 }, { stepNumber: 5, instruction: 'Garnish with coriander leaves and serve hot', estimatedTime: 2 }, { stepNumber: 6, instruction: 'Serve hot with roti or paratha', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut paneer into cubes', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Heat oil and saute chopped onions, garlic, and ginger', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Add tomatoes, garam masala, and kashmiri chili powder', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Cook until tomatoes are soft and oil separates', estimatedTime: 8 }, { stepNumber: 5, instruction: 'Add paneer cubes and cook for 5 minutes, tossing gently', estimatedTime: 5 }, { stepNumber: 6, instruction: 'Serve hot with rice or roti', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Boil and cube potatoes', estimatedTime: 10 }, { stepNumber: 2, instruction: 'Whisk yogurt with turmeric, cumin, and coriander leaves', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Heat oil and saute green chili and onion', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Lower heat and add yogurt mixture, stirring constantly', estimatedTime: 5 }, { stepNumber: 5, instruction: 'Add boiled potatoes and cook on low heat for 10 minutes', estimatedTime: 10 }, { stepNumber: 6, instruction: 'Serve with steamed rice or roti', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Finely chop onions into thin strips', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Mix gram flour with green chili, coriander, cumin, and salt to make a thick batter', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Add chopped onions to the batter and mix well', estimatedTime: 2 }, { stepNumber: 4, instruction: 'Heat oil and drop spoonfuls into hot oil', estimatedTime: 2 }, { stepNumber: 5, instruction: 'Fry until golden and crispy on both sides', estimatedTime: 8 }, { stepNumber: 6, instruction: 'Serve hot with green chutney and tea', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut paneer into cubes', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Heat butter and saute onions until caramelized', estimatedTime: 8 }, { stepNumber: 3, instruction: 'Add more chopped onions, tomatoes, garam masala, turmeric, and garlic. Cook until soft', estimatedTime: 8 }, { stepNumber: 4, instruction: 'Add cream and paneer. Cook for 5 minutes', estimatedTime: 5 }, { stepNumber: 5, instruction: 'Garnish with cream and serve hot with naan or rice', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cube potatoes and bell peppers', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Heat oil and add cumin, turmeric, and coriander powder', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Add onions and saute until translucent', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Add potatoes and bell peppers. Cook covered for 12 minutes', estimatedTime: 12 }, { stepNumber: 5, instruction: 'Garnish with coriander and serve with roti', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut paneer into cubes', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Heat oil and saute onions, garlic, and ginger', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Add bell peppers, tomatoes, and tomato sauce. Cook for 5 minutes', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Add garam masala and cook until masala is thick', estimatedTime: 5 }, { stepNumber: 5, instruction: 'Add paneer, toss well, and cook for 3 minutes on high heat', estimatedTime: 3 }, { stepNumber: 6, instruction: 'Serve hot with rice or naan', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Wash and chop fenugreek leaves', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Peel and cube potatoes', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Heat oil and add cumin, turmeric, and garlic', estimatedTime: 2 }, { stepNumber: 4, instruction: 'Add potatoes and cook for 5 minutes', estimatedTime: 5 }, { stepNumber: 5, instruction: 'Add fenugreek leaves, cover, and cook for 10 minutes', estimatedTime: 10 }, { stepNumber: 6, instruction: 'Serve hot with roti or paratha', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut paneer into cubes', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Blend tomatoes and onions into a smooth puree', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Heat butter and saute cashew paste until golden', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Add puree, garam masala, and cook until oil separates', estimatedTime: 10 }, { stepNumber: 5, instruction: 'Add cream, paneer, and cook for 8 minutes on low heat', estimatedTime: 8 }, { stepNumber: 6, instruction: 'Garnish with cream and serve with naan or rice', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Peel and cube potatoes and eggplant', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Heat oil and add cumin, turmeric, and coriander powder', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Add onions and saute until golden', estimatedTime: 5 }, { stepNumber: 4, instruction: 'Add potatoes and eggplant. Cook covered for 15 minutes', estimatedTime: 15 }, { stepNumber: 5, instruction: 'Garnish with coriander and serve with roti', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut paneer into squares', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Blend almonds and cashews into a smooth paste', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Heat ghee and saute onion-tomato puree with spices', estimatedTime: 8 }, { stepNumber: 4, instruction: 'Add nut paste, cream, saffron, and cook until thick', estimatedTime: 10 }, { stepNumber: 5, instruction: 'Add paneer and simmer for 8 minutes on low heat', estimatedTime: 8 }, { stepNumber: 6, instruction: 'Garnish with saffron and serve with naan', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Wash and chop spinach', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Peel and cube potatoes', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Heat oil and saute garlic, ginger, green chili, and turmeric', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Add potatoes and cook for 5 minutes', estimatedTime: 5 }, { stepNumber: 5, instruction: 'Add spinach, cook covered for 8 minutes until wilted', estimatedTime: 8 }, { stepNumber: 6, instruction: 'Serve hot with roti or paratha', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Cut paneer into cubes', estimatedTime: 3 }, { stepNumber: 2, instruction: 'Mix flour, corn flour, green chili, garlic, ginger, soy sauce, and water into a thick batter', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Coat paneer cubes in the batter', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Deep fry in hot oil until crispy and golden', estimatedTime: 8 }, { stepNumber: 5, instruction: 'Toss in a spicy sauce made with chili, garlic, and soy sauce', estimatedTime: 3 }, { stepNumber: 6, instruction: 'Garnish with spring onions and serve hot as a snack', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Boil and cube potatoes', estimatedTime: 10 }, { stepNumber: 2, instruction: 'Heat oil in a pan and add cumin seeds', estimatedTime: 2 }, { stepNumber: 3, instruction: 'Add potatoes and red chili flakes. Toss well', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Fry on medium heat for 10 minutes until crispy', estimatedTime: 10 }, { stepNumber: 5, instruction: 'Garnish with coriander leaves', estimatedTime: 2 }, { stepNumber: 6, instruction: 'Serve as a side dish with roti or paratha', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Make stuffing by mashing paneer with potato, green chili, ginger, and coriander', estimatedTime: 10 }, { stepNumber: 2, instruction: 'Roll out wheat dough into flat circles', estimatedTime: 5 }, { stepNumber: 3, instruction: 'Place stuffing in center and seal edges carefully', estimatedTime: 3 }, { stepNumber: 4, instruction: 'Roll out gently and cook on tawa with ghee and butter', estimatedTime: 8 }, { stepNumber: 5, instruction: 'Flip and cook both sides until golden brown', estimatedTime: 5 }, { stepNumber: 6, instruction: 'Serve hot with butter and pickle', estimatedTime: 2 }],
  [{ stepNumber: 1, instruction: 'Peel and cube potatoes and chop onions', estimatedTime: 5 }, { stepNumber: 2, instruction: 'Mix gram flour with green chili, coriander powder, cumin, and salt to make batter', estimatedTime: 3 }, { stepNumber: 3, instruction: 'Add potatoes and onions to the batter and mix well', estimatedTime: 2 }, { stepNumber: 4, instruction: 'Heat oil and drop spoonfuls into hot oil', estimatedTime: 2 }, { stepNumber: 5, instruction: 'Fry until golden and crispy on both sides', estimatedTime: 8 }, { stepNumber: 6, instruction: 'Serve hot with green chutney and tea', estimatedTime: 2 }],
];

async function main() {
  console.log('Seeding recipes...');

  const existingCount = await prisma.recipe.count();
  console.log(`Existing recipes in database: ${existingCount}`);

  if (existingCount > 0) {
    console.log('Clearing existing recipes...');
    await prisma.userRecipeStep.deleteMany();
    await prisma.userRecipeIngredient.deleteMany();
    await prisma.userRecipe.deleteMany();
    await prisma.review.deleteMany();
    await prisma.savedRecipe.deleteMany();
    await prisma.collection.deleteMany();
    await prisma.shoppingList.deleteMany();
    await prisma.mealPlan.deleteMany();
    await prisma.recipeStep.deleteMany();
    await prisma.recipeIngredient.deleteMany();
    await prisma.recipe.deleteMany();
    await prisma.chatMessage.deleteMany();
    await prisma.ingredient.deleteMany();
    await prisma.session.deleteMany();
    await prisma.account.deleteMany();
    await prisma.user.deleteMany();
    console.log('Cleared all existing data.');
  }

  for (let i = 0; i < recipes.length; i++) {
    const recipe = recipes[i];
    const rid = crypto.randomUUID();

    await prisma.recipe.create({
      data: {
        id: rid,
        title: recipe.title,
        description: recipe.description,
        cuisine: recipe.cuisine,
        mealType: recipe.mealType,
        cookingTime: recipe.cookingTime,
        servings: recipe.servings,
        difficulty: recipe.difficulty,
        nutritionalInfo: recipe.nutritionalInfo,
        image: recipe.image,
        youtubeUrl: recipe.youtubeUrl || null,
        source: 'catalog',
      },
    });

    await prisma.recipeIngredient.createMany({
      data: recipeIngredients[i].map(ing => ({
        id: crypto.randomUUID(),
        recipeId: rid,
        ingredient: ing.ingredient,
        quantity: ing.quantity,
        unit: ing.unit || null,
      })),
    });

    await prisma.recipeStep.createMany({
      data: recipeSteps[i].map(step => ({
        id: crypto.randomUUID(),
        recipeId: rid,
        stepNumber: step.stepNumber,
        instruction: step.instruction,
        estimatedTime: step.estimatedTime,
      })),
    });

    console.log(`  Seeded: ${recipe.title}`);
  }

  console.log(`Seeded ${recipes.length} recipes successfully!`);
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
